### ISSUE TITLE
The deployed page is broken

### ISSUE THREAD

**Issue by FilipMessa** [fatman-/learn-draftjs#1]
This is a really great source of information about the draftjs, thanks for that, but currently, the online page is broken. https://learn-draftjs.now.sh/

<img width="775" alt="Screenshot 2020-08-17 at 10 51 43" src="https://user-images.githubusercontent.com/6354326/90377079-bf186b00-e077-11ea-97e2-cf2b09207304.png">

**Comment by sibelius** [comment]
ping

**Comment by saiki-k** [comment]
Hello! The URL where this application is hosted at has been changed to "[learn-draftjs-now.vercel.app](https://learn-draftjs-now.vercel.app)".
