### ISSUE TITLE
I've got this error 

### ISSUE THREAD

**Issue by sibelius** [fatman-/learn-draftjs#2]
Module not found: `/learn-draftjs/src/components/DraftTuts/Introduction/Editor.js` does not match the corresponding path on disk `editor.js`.

**Comment by saiki-k** [comment]
This was a strange error indeed. I am not sure how the capitalization got changed. But I remember pulling the project, and doing a couple of things on the specified file -- removed it from git, added it back again -- and I hope that fixed it.
